services:
  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate --noinput && python manage.py seed_demo_data && gunicorn exam_system.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    env_file:
      - ./backend/.env
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: localhost,127.0.0.1,backend
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      SQLITE_PATH: /app/data/db.sqlite3
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    depends_on:
      redis:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  sqlite_data:
